config/routes.rb
Rails.application.routes.draw do
  resources :meublogs

end

app/models/meublog.rb
# encoding: UTF-8
class Meublog < ActiveRecord::Base
	validates :title, presence: { :message => "não pode ficar em branco." },
                    length: { minimum: 5 , :message => " deve ter no mínimo 5 caracteres."}
end

app/controllers/application_controller.rb
# encoding: UTF-8
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/meublogs_controller.rb
# encoding: UTF-8
class MeublogsController < ApplicationController
  before_action :set_meublog, only: [:show, :edit, :update, :destroy]

  http_basic_authenticate_with name: "carol", password: "1234", except: [:index, :show]
  
  # GET /meublogs
  # GET /meublogs.json
  def index
    @meublogs = Meublog.all
  end

  # GET /meublogs/1
  # GET /meublogs/1.json
  def show
  end

  # GET /meublogs/new
  def new
    @meublog = Meublog.new
  end

  # GET /meublogs/1/edit
  def edit
  end

  # POST /meublogs
  # POST /meublogs.json
  def create
    @meublog = Meublog.new(meublog_params)

    respond_to do |format|
      if @meublog.save
		flash[:sucess] = 'A postagem foi criada com sucesso.'
        format.html { redirect_to @meublog }
        format.json { render :show, status: :created, location: @meublog }
      else
		flash[:danger] = 'Houve um problema ao criar a postagem.'
        format.html { render :new }
        format.json { render json: @meublog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meublogs/1
  # PATCH/PUT /meublogs/1.json
  def update
    respond_to do |format|
      if @meublog.update(meublog_params)
	    flash[:sucess] = 'A postagem foi alterada com sucesso.'
        format.html { redirect_to @meublog }
        format.json { render :show, status: :ok, location: @meublog }
      else
		flash[:danger] = 'Houve um problema ao alterar a postagem.'
        format.html { render :edit }
        format.json { render json: @meublog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meublogs/1
  # DELETE /meublogs/1.json
  def destroy
    @meublog.destroy
    respond_to do |format|
	  flash[:sucess] = 'A postagem foi removida com sucesso.'
      format.html { redirect_to @meublog }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meublog
      @meublog = Meublog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meublog_params
      params.require(:meublog).permit(:title, :text)
    end
end

app/helpers/application_helper.rb
# encoding: UTF-8
module ApplicationHelper
end

app/helpers/meublogs_helper.rb
# encoding: UTF-8
module MeublogsHelper
 
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'shared/navigation' %>
	<div id="main-container" class="container">
      <div class="row">
		<% flash.each do |name, msg| -%>
			<%= content_tag :div, msg, class: "alert alert-#{name}" %>
		<% end -%>
        <div class="col-xs-4">
          <h1>Meu Blog de Rails</h1>
        </div>
        <div class="col-xs-9">
          <%= yield %>
        </div>
      </div>
    </div>
</body>
</html>

app/views/meublogs/_form.html.erb
<%= form_for(@meublog, html: {class: 'form-horizontal'}) do |f| %>
  <% if @meublog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meublog.errors.count, "erro") %> encontrados:</h2>
      <ul>
      <% @meublog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label "Título", class: 'col-sm-2 control-label' %>
	<div class="col-sm-10">
		<%= f.text_field :title, class: 'form-control' %>
	</div>
  </div>
  <div class="field form-group">
    <%= f.label "Texto", class: 'col-sm-2 control-label' %>
	<div class="col-sm-10">
		<%= f.text_area :text, class: 'form-control' %>
	</div>
  </div>
  <div class="actions form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<%= f.submit "Salvar", class: 'btn-sm' %>
	</div>
  </div>
<% end %>

app/views/meublogs/edit.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li><%= link_to 'Listagem', meublogs_path %></li>
  <li><%= link_to 'Nova Postagem', new_meublog_path %></li>
  <li><%= link_to 'Exibir', @meublog %></li>
  <li class="active"><%= link_to 'Alterar', edit_meublog_path(@meublog) %></li>
</ul>

<h2>Alterar Postagem</h2>

<%= render 'form' %>

<%= link_to meublogs_path, class: 'btn btn-info btn-xs' do %>
	<i class="glyphicon glyphicon-arrow-left"></i> Voltar
<% end %>

app/views/meublogs/index.html.erb
<p id="notice"><%= notice %></p>

<ul class="nav nav-tabs" role="tablist">
  <li class="active"><%= link_to 'Listagem', meublogs_path %></li>
  <li><%= link_to 'Nova Postagem', new_meublog_path %></li>
</ul>

<h2>Artigos do Blog</h2>

<table class="table">
  <thead>
    <tr>
      <th>Título</th>
      <th>Texto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  	<% @meublogs.each do |meublog| %>
		<tr>
			<td><%= meublog.title %></td>
			<td><%= meublog.text %></td>
			<td>
				<%= link_to meublog, class: 'btn btn-primary btn-xs' do %>
					<i class="glyphicon glyphicon-list-alt"></i> Exibir
				<% end %>
			</td>
			<td>
				<%= link_to edit_meublog_path(meublog), class: 'btn btn-info btn-xs' do %>
					<i class="glyphicon glyphicon-pencil"></i> Alterar
				<% end %>
			</td>
			<td>
				<%= link_to meublog, method: :delete, data: { confirm: 'Você realmente deseja remover a Postagem?' }, class: 'btn btn-danger btn-xs' do %>
					<i class="glyphicon glyphicon-trash"></i> Remover
				<% end %>
			</td>
		</tr>
	<% end %>		
		<tr>
			
		</tr>
  </tbody>
</table>

<br>

<%= link_to new_meublog_path, class: 'btn btn-success' do %>
  <i class="glyphicon glyphicon-plus"></i> Novo
<% end %>

app/views/meublogs/new.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li><%= link_to 'Listagem', meublogs_path %></li>
  <li class="active"><%= link_to 'Nova Postagem', new_meublog_path %></li>
</ul>

<h2>Nova Postagem</h2>

<%= render 'form' %>

<%= link_to meublogs_path, class: 'btn btn-info btn-xs' do %>
	<i class="glyphicon glyphicon-arrow-left"></i> Voltar
<% end %>

app/views/meublogs/show.html.erb
<p id="notice"><%= notice %></p>

<ul class="nav nav-tabs" role="tablist">
  <li><%= link_to 'Listagem', meublogs_path %></li>
  <li><%= link_to 'Nova Postagem', new_meublog_path %></li>
  <li class="active"><%= link_to 'Exibir', @meublog %></li>
  <li><%= link_to 'Alterar', edit_meublog_path(@meublog) %></li>
</ul>

<h2>Exibir Postagem</h2>

<table class="table-reponsive">
<tr>
  <td>
	<h3>Título:</h3>
	<p><%= @meublog.title %></p>
  </td>  
</tr>

<tr>
  <td>
	<h3>Texto:</h3>
	<p><%= @meublog.text %></p>
  </td>
</tr>

</table>
<br>
<div>

<%= link_to meublogs_path, class: 'btn btn-info btn-xs' do %>
	<i class="glyphicon glyphicon-arrow-left"></i> Voltar
<% end %>

</div>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/meublogs">Meu Blog</a>
	  <a class="navbar-brand" href="/meublogs">Novidades</a>
	  <a class="navbar-brand" href="/meublogs">Categorias</a>
	  <a class="navbar-brand" href="/meublogs">Relatórios</a>
    </div>
  </div>
</nav>